### ISSUE TITLE
Add Karmada starting examples with killercoda

### ISSUE THREAD

**Issue by JadeFlute0127** [karmada-io/playground#1]
**What would you like to be added:**
Add Karmada starting examples with [killercoda](https://killercoda.com/), including a CLI installation example and script installation example, both containing installation and deploying workload to multi-clusters steps.

**Tasks & deadline:**

1. Implement CLI installation example, with deploying workload to multi-clusters steps.
   * [x] Implement CLI installation example (deadline: March 26, 2023)
   * [x] Using CLI to implement the steps of deploying workloads to multi-clusters (deadline: March 29, 2023)
2. Implement script installation example, with deploying workload to multi-clusters steps.
   * [x] Implement script installation example (deadline: April 2, 2023)
   * [x] Using scripts to implement the steps of deploying workloads to multi-clusters (deadline: April 6, 2023)
3. Update Karmada official website docs, indicating users can quickly try Karmada with killercoda.
   * [ ] Update Karmada official website docs (deadline: April 9, 2023)

**Comment by jwcesign** [comment]
Great! However, there is no need to hurry as the mid-checking time is on April 12th and the final checking will take place in May.

**Comment by jwcesign** [comment]
All is finished.
/close
