### ISSUE TITLE
Add Killercoda examples：Use Karmada-search to experience multi-cloud search

### ISSUE THREAD

**Issue by JadeFlute0127** [karmada-io/playground#9]
**What would you like to be added:**
Add Karmada-search usage examples with [killercoda](https://killercoda.com/), including use Karmada-search to experience multi-cloud search steps.

**Tasks:**

1. Implement propagate Deployment example. 
   * [ ] Install karmada-search component in the Karmada control plane.
   * [ ] Cache Deployment resources across multiple clusters.
   * [ ] Use OpenSearch to graphically retrieve Kubernetes resources.

**Comment by RainbowMango** [comment]
This comment is just for testing new Prowbot, regarding to https://github.com/karmada-io/karmada/issues/4637

/kind feature
